name: Warn for Empty Strings

on: [pull_request]

permissions:
  issues: write
  pull-requests: write

jobs:
  check-empty-strings:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Find empty strings in TypeScript files
        id: find_empty_strings
        run: |
          output=$(grep -Rn --include=\*.ts "''\|\"\"" --exclude-dir={node_modules,dist,out} .)
          if [ -z "$output" ]; then
            echo "::set-output name=results::No empty strings found."
          else
            echo "::set-output name=results::${output//$'\n'/%0A}"
          fi
        continue-on-error: true

      - name: Post comment with findings
        if: steps.find_empty_strings.outputs.results != 'No empty strings found.'
        uses: actions/github-script@v6
        with:
          script: |
            const results = `${{ steps.find_empty_strings.outputs.results }}`.replace(/%0A/g, '\n');
            const commentBody = `## 🚨 Empty String Usage Detected 🚨\n\n` +
                                `The following occurrences of empty strings were detected. Please review them to ensure their usage is necessary:\n\n` +
                                '```plaintext\n' + results + '\n```\n\n' +
                                'Consider replacing empty strings with more descriptive alternatives if applicable.';
            const prNumber = context.payload.pull_request.number;

            github.rest.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });
