name: Warn for Empty Strings

on: [push, pull_request, workflow_dispatch]

jobs:
  check-empty-strings:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for empty strings in TypeScript files
        id: check_empty
        run: |
          output=$(grep -Rn --include=\*.ts "''\|\"\"" --exclude-dir={node_modules,dist,out} .)
          if [ -z "$output" ]; then
            echo "No empty strings found."
            echo "::set-output name=found::false"
          else
            echo "$output"
            echo "::set-output name=found::true"
            echo "::set-output name=result::$(echo "$output")"
          fi
        continue-on-error: true

      - name: Post comment if empty strings are found
        if: steps.check_empty.outputs.found == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            const output = `${{ steps.check_empty.outputs.result }}`;
            const formattedOutput = output.split('\n').map(line => line.trim()).join('\n');
            const commentBody = `**Empty strings found in TypeScript files**\n` +
                                'Please review the usage of empty strings to ensure it is necessary. ' +
                                'Below are the occurrences:\n' +
                                '```\n' + formattedOutput + '\n```';
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody,
            });
